# Generated by Django 3.1.5 on 2021-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupon_code',
            field=models.CharField(blank=True, default=None, max_length=264, null=True),
        ),
    ]
