# Generated by Django 3.1.5 on 2021-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0002_product_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupon_discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount in %'),
        ),
    ]
