# Generated by Django 3.1.5 on 2021-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0003_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.IntegerField(verbose_name='Coupon discount in percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
