# Generated by Django 3.1.5 on 2021-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates weather this user should be treated as active. Unselect this insist of deleting account. ', verbose_name='active'),
        ),
    ]
