# Generated by Django 3.1.5 on 2021-01-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_auto_20210128_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(blank=True, default=False, help_text='Designates weather this user should be treated as a seller. Unselect this insist of a normal account.', null=True, verbose_name='seller_status'),
        ),
    ]
