# Generated by Django 3.1.5 on 2021-01-28 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_auto_20210128_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=264)),
                ('shop_address', models.TextField(max_length=350)),
                ('shop_type', models.CharField(choices=[('electronics', 'Electronics'), ('accessories', 'Accessories'), ('cloths', 'Cloths'), ('groceries', 'Groceries'), ('others', 'Others')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
